name: Build pull request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Restore release keystore
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > app/keystore.jks
          ls -la app/keystore.jks

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build and Sign Release APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ENTRY_ALIAS: ${{ secrets.KEYSTORE_ENTRY_ALIAS }}
          KEYSTORE_ENTRY_PASSWORD: ${{ secrets.KEYSTORE_ENTRY_PASSWORD }}
          _JAVA_OPTIONS: "-Djava.awt.headless=true"
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Rename APK
        run: |
          for f in app/build/outputs/apk/release/*-release.apk; do
            mv "$f" "${f/-release/}"
          done

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/outputs/apk/release/*.apk
