name: Compile pull request

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build Debug APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          _JAVA_OPTIONS: "-Djava.awt.headless=true"
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug -PnoProguard -PsignAsDebug --stacktrace
